name: metropolitan-test

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-test
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pass4321!"
      MSSQL_PID: "Developer"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
